### ISSUE TITLE
Add a way to build an AStr from a `Display` implementation

### ISSUE THREAD

**Issue by edgarogh** [lperlaki/astr-rs#1]
### Context

The primary goal of this crate seems to be to avoid needless allocations for small constant-sized strings. Some of these strings can include IDs, UUIDs, PINs, MAC addresses, RGB hex colors etc. which may have a compact in-memory representation and a less compact string representation whose length is strictly constant (i.e. a UUID will always be 36 bytes long in string form). The "compact" representation often comes with a `Debug` or `Display` implementation which is solely responsible for the conversion.

### Feature request

I think it would be convenient to have a way to build an `AStr` from any type that implements `Display`, given an expected total length. If the `Display` implementation writes too few or too much characters, an error is returned instead.

### Implementation

The additional constructor could look something like `AStr::from_fmt(fmt: &dyn std::fmt::Display)`. An equivalent method for the `Debug` trait is superfluous as calling `format_args!("{something:?}")` will return a `Display`able `Arguments<'_>` instance that calls the `Debug` implementation of "something". With a macro as explained below, you wouldn't even call this function manually most of the time.

I have a working implementation in one of my projects, which also comes with a `format_astr!()` macro to build `AStr`s even faster. I would love to open a PR, but if you're interested, I would like guidance on the exact constructor name and signature that you would like, whether a `format_astr!` macro is in-scope for this PR, and whether or not the macro should take an optional parameter to specify the expected length (or else, type inference would do the job alone).

**Comment by lperlaki** [comment]
sound like a good idea, I would be happy to review a pull request. 

I think a function signature like `AStr::try_from_fmt(fmt: impl core::fmt::Display) -> Result<Self, Error>`
would be the most general and we can built a panicking function and the macro from that.

**Comment by lperlaki** [comment]
just published a new version with this feature.
@edgarogh thank you for implementing it.
